package com.com.cskaoyan.newsproject.bean;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment_t.cid
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment_t.content
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment_t.created_date
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment_t.news_id
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment_t.comment_user_id
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    private Integer commentUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment_t.cid
     *
     * @return the value of news_comment_t.cid
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment_t.cid
     *
     * @param cid the value for news_comment_t.cid
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment_t.content
     *
     * @return the value of news_comment_t.content
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment_t.content
     *
     * @param content the value for news_comment_t.content
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment_t.created_date
     *
     * @return the value of news_comment_t.created_date
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment_t.created_date
     *
     * @param createdDate the value for news_comment_t.created_date
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment_t.news_id
     *
     * @return the value of news_comment_t.news_id
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment_t.news_id
     *
     * @param newsId the value for news_comment_t.news_id
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment_t.comment_user_id
     *
     * @return the value of news_comment_t.comment_user_id
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public Integer getCommentUserId() {
        return commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment_t.comment_user_id
     *
     * @param commentUserId the value for news_comment_t.comment_user_id
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    public void setCommentUserId(Integer commentUserId) {
        this.commentUserId = commentUserId;
    }
}