package com.com.cskaoyan.newsproject.bean;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.id
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.title
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.link
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.image
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.like_count
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.user_id
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private Integer userId;
    private Integer commentCount;

    public Integer getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_news_t.created_date
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.id
     *
     * @return the value of news_news_t.id
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.id
     *
     * @param id the value for news_news_t.id
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.title
     *
     * @return the value of news_news_t.title
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.title
     *
     * @param title the value for news_news_t.title
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.link
     *
     * @return the value of news_news_t.link
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.link
     *
     * @param link the value for news_news_t.link
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.image
     *
     * @return the value of news_news_t.image
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.image
     *
     * @param image the value for news_news_t.image
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.like_count
     *
     * @return the value of news_news_t.like_count
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.like_count
     *
     * @param likeCount the value for news_news_t.like_count
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.user_id
     *
     * @return the value of news_news_t.user_id
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.user_id
     *
     * @param userId the value for news_news_t.user_id
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_news_t.created_date
     *
     * @return the value of news_news_t.created_date
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_news_t.created_date
     *
     * @param createdDate the value for news_news_t.created_date
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public String toString() {
        return "News{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", link='" + link + '\'' +
                ", image='" + image + '\'' +
                ", likeCount=" + likeCount +
                ", userId=" + userId +
                ", commentCount=" + commentCount +
                ", createdDate=" + createdDate +
                '}';
    }
}