package com.com.cskaoyan.newsproject.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_user_t.id
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_user_t.username
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_user_t.password
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_user_t.head_url
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    private String headUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_user_t.id
     *
     * @return the value of news_user_t.id
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_user_t.id
     *
     * @param id the value for news_user_t.id
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_user_t.username
     *
     * @return the value of news_user_t.username
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_user_t.username
     *
     * @param username the value for news_user_t.username
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_user_t.password
     *
     * @return the value of news_user_t.password
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_user_t.password
     *
     * @param password the value for news_user_t.password
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_user_t.head_url
     *
     * @return the value of news_user_t.head_url
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_user_t.head_url
     *
     * @param headUrl the value for news_user_t.head_url
     *
     * @mbg.generated Wed Dec 19 21:05:41 CST 2018
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", headUrl='" + headUrl + '\'' +
                '}';
    }
}