package com.com.cskaoyan.newsproject.dao;


import com.com.cskaoyan.newsproject.bean.Comment;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment_t
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment_t
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment_t
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment_t
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    Comment selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment_t
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment_t
     *
     * @mbg.generated Wed Dec 19 22:49:45 CST 2018
     */
    int updateByPrimaryKey(Comment record);

    List<Comment> findCommentByNewsIdFromDB(@Param("newsID") String newsID);
}