package com.com.cskaoyan.newsproject.dao;


import com.com.cskaoyan.newsproject.bean.News;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_news_t
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_news_t
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_news_t
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_news_t
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_news_t
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_news_t
     *
     * @mbg.generated Wed Dec 19 16:02:32 CST 2018
     */
    int updateByPrimaryKey(News record);

    List<News> findAllNewsFromDB();
}